server:
  port: 8080
  address: 0.0.0.0
spring:
  datasource:
    url: jdbc:postgresql://database-1-instance-1.c0tqu2cy6o3j.us-east-1.rds.amazonaws.com:5432/drivingschool
    username: postgres_manudev
    password:  PostgresDev
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource.hikari:
    maximum-pool-size: 10
    connection-timeout: 30000
    idle-timeout: 600000
    max-lifetime: 1800000